name: pllabs-development

services:
  database:
    image: postgres:16
    container_name: database
    volumes:
      - pllabs_database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=pllabs
      - POSTGRES_PASSWORD=pllabs
      - POSTGRES_DB=pllabs
    ports:
      - 5432:5432

  inbucket:
    image: inbucket/inbucket
    container_name: mailserver
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100

volumes:
  pllabs_database: